#!/bin/bash
DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

ENTITY_DIR="$DIR/../temp/generated-entities"
mkdir -p "$ENTITY_DIR"
php $DIR/../vendor/bin/doctrine-module orm:generate:entities "$ENTITY_DIR"
